@extends('layouts.app')
@section('title', 'Rapports d\'activité - BlackCine Admin')
@section('content')
<div class="mb-6 flex justify-between items-center"><div><h1 class="text-3xl font-bold text-gray-800">Rapports d'activité</h1><p class="text-gray-600 mt-2">Vue d'ensemble de l'activité de la plateforme</p></div><div class="flex gap-3"><button class="bg-white border border-gray-300 text-gray-700 px-4 py-2 rounded-lg hover:bg-gray-50 flex items-center transition-colors"><span class="material-symbols-outlined mr-2">calendar_today</span>Derniers 30 jours</button><button class="bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700 flex items-center transition-colors shadow-sm"><span class="material-symbols-outlined mr-2">download</span>Exporter PDF</button></div></div>

<!-- Stats -->
<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
<div class="bg-white rounded-lg shadow-sm border border-gray-100 p-4"><div class="flex items-center justify-between"><div><p class="text-sm text-gray-500">Visites totales</p><p class="text-2xl font-bold text-gray-900">124,592</p></div><div class="bg-blue-50 p-3 rounded-full"><span class="material-symbols-outlined text-blue-600">visibility</span></div></div><div class="mt-3 flex items-center text-sm"><span class="text-green-600 flex items-center font-medium"><span class="material-symbols-outlined text-sm mr-1">trending_up</span>+12.5%</span><span class="text-gray-500 ml-2">vs mois dernier</span></div></div>
<div class="bg-white rounded-lg shadow-sm border border-gray-100 p-4"><div class="flex items-center justify-between"><div><p class="text-sm text-gray-500">Nouveaux utilisateurs</p><p class="text-2xl font-bold text-gray-900">8,430</p></div><div class="bg-green-50 p-3 rounded-full"><span class="material-symbols-outlined text-green-600">group_add</span></div></div><div class="mt-3 flex items-center text-sm"><span class="text-green-600 flex items-center font-medium"><span class="material-symbols-outlined text-sm mr-1">trending_up</span>+5.2%</span><span class="text-gray-500 ml-2">vs mois dernier</span></div></div>
<div class="bg-white rounded-lg shadow-sm border border-gray-100 p-4"><div class="flex items-center justify-between"><div><p class="text-sm text-gray-500">Abonnements Premium</p><p class="text-2xl font-bold text-gray-900">1,240</p></div><div class="bg-purple-50 p-3 rounded-full"><span class="material-symbols-outlined text-purple-600">workspace_premium</span></div></div><div class="mt-3 flex items-center text-sm"><span class="text-green-600 flex items-center font-medium"><span class="material-symbols-outlined text-sm mr-1">trending_up</span>+8.1%</span><span class="text-gray-500 ml-2">vs mois dernier</span></div></div>
<div class="bg-white rounded-lg shadow-sm border border-gray-100 p-4"><div class="flex items-center justify-between"><div><p class="text-sm text-gray-500">Tickets Support</p><p class="text-2xl font-bold text-gray-900">342</p></div><div class="bg-red-50 p-3 rounded-full"><span class="material-symbols-outlined text-red-600">support_agent</span></div></div><div class="mt-3 flex items-center text-sm"><span class="text-red-600 flex items-center font-medium"><span class="material-symbols-outlined text-sm mr-1">trending_down</span>-2.4%</span><span class="text-gray-500 ml-2">vs mois dernier</span></div></div>
</div>

<!-- Graphiques -->
<div class="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
<div class="lg:col-span-2 bg-white rounded-lg shadow-sm border border-gray-100 p-6"><h3 class="text-lg font-bold text-gray-800 mb-4 flex items-center"><span class="material-symbols-outlined mr-2 text-red-600">bar_chart</span>Trafic et Engagement</h3><div class="h-80 bg-gray-50 rounded flex items-center justify-center border border-dashed border-gray-300"><div class="text-center"><span class="material-symbols-outlined text-4xl text-gray-400 mb-2 block">show_chart</span><p class="text-gray-500">Graphique d'activité (Chart.js)</p></div></div></div>

<div class="bg-white rounded-lg shadow-sm border border-gray-100 p-6"><h3 class="text-lg font-bold text-gray-800 mb-4 flex items-center"><span class="material-symbols-outlined mr-2 text-red-600">notifications_active</span>Activités Récentes</h3><div class="space-y-4">
<div class="flex items-start"><div class="flex-shrink-0"><div class="h-8 w-8 rounded-full bg-blue-100 flex items-center justify-center"><span class="material-symbols-outlined text-blue-600 text-sm">person_add</span></div></div><div class="ml-3 w-0 flex-1"><p class="text-sm font-medium text-gray-900">Nouvel utilisateur</p><p class="text-xs text-gray-500">Jean Dupont via Google</p><p class="text-xs text-gray-400 mt-1">Il y a 5 min</p></div></div>
<div class="flex items-start"><div class="flex-shrink-0"><div class="h-8 w-8 rounded-full bg-green-100 flex items-center justify-center"><span class="material-symbols-outlined text-green-600 text-sm">shopping_cart</span></div></div><div class="ml-3 w-0 flex-1"><p class="text-sm font-medium text-gray-900">Nouvelle commande</p><p class="text-xs text-gray-500">Commande #12345 (24.99€)</p><p class="text-xs text-gray-400 mt-1">Il y a 12 min</p></div></div>
<div class="flex items-start"><div class="flex-shrink-0"><div class="h-8 w-8 rounded-full bg-yellow-100 flex items-center justify-center"><span class="material-symbols-outlined text-yellow-600 text-sm">star</span></div></div><div class="ml-3 w-0 flex-1"><p class="text-sm font-medium text-gray-900">Nouvel avis</p><p class="text-xs text-gray-500">5★ sur "Inception"</p><p class="text-xs text-gray-400 mt-1">Il y a 25 min</p></div></div>
<div class="flex items-start"><div class="flex-shrink-0"><div class="h-8 w-8 rounded-full bg-red-100 flex items-center justify-center"><span class="material-symbols-outlined text-red-600 text-sm">warning</span></div></div><div class="ml-3 w-0 flex-1"><p class="text-sm font-medium text-gray-900">Tentative échouée</p><p class="text-xs text-gray-500">IP: 192.168.1.1</p><p class="text-xs text-gray-400 mt-1">Il y a 45 min</p></div></div>
<div class="pt-4 text-center"><a href="{{ route('admin.support.logs.index') }}" class="text-sm text-red-600 hover:text-red-700 font-medium">Voir tous les logs →</a></div>
</div></div>
</div>

<!-- Table -->
<div class="bg-white rounded-lg shadow-sm border border-gray-100 overflow-hidden"><div class="px-6 py-4 border-b border-gray-200"><h3 class="text-lg font-bold text-gray-800 flex items-center"><span class="material-symbols-outlined mr-2 text-red-600">analytics</span>Pages les plus visitées</h3></div><div class="overflow-x-auto"><table class="w-full"><thead class="bg-gray-50"><tr><th class="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Page</th><th class="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Vues</th><th class="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Temps moyen</th><th class="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Taux rebond</th></tr></thead><tbody class="divide-y divide-gray-200"><tr class="hover:bg-gray-50 transition"><td class="px-6 py-4 text-sm font-medium text-gray-900">/home</td><td class="px-6 py-4 text-sm text-gray-600">45,230</td><td class="px-6 py-4 text-sm text-gray-600">00:45</td><td class="px-6 py-4 text-sm text-green-600 font-medium">32%</td></tr><tr class="hover:bg-gray-50 transition"><td class="px-6 py-4 text-sm font-medium text-gray-900">/catalog/movies</td><td class="px-6 py-4 text-sm text-gray-600">28,105</td><td class="px-6 py-4 text-sm text-gray-600">02:15</td><td class="px-6 py-4 text-sm text-green-600 font-medium">24%</td></tr><tr class="hover:bg-gray-50 transition"><td class="px-6 py-4 text-sm font-medium text-gray-900">/subscription</td><td class="px-6 py-4 text-sm text-gray-600">12,450</td><td class="px-6 py-4 text-sm text-gray-600">01:30</td><td class="px-6 py-4 text-sm text-yellow-600 font-medium">45%</td></tr></tbody></table></div></div>
@endsection
