@extends('layouts.app')
@section('title', 'Exports - BlackCine Admin')
@section('content')
<div class="mb-6"><h1 class="text-3xl font-bold text-gray-800">Exports de données</h1><p class="text-gray-600 mt-2">Exportez vos données en différents formats</p></div>

<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
<div class="bg-white rounded-lg shadow-sm border border-gray-100 p-6 hover:shadow-md transition-shadow"><div class="flex items-center justify-between mb-4"><div class="bg-blue-50 p-3 rounded-full"><span class="material-symbols-outlined text-blue-600">group</span></div><span class="px-2.5 py-1 bg-blue-100 text-blue-800 text-xs font-medium rounded-full">Disponible</span></div><h3 class="text-lg font-bold text-gray-900 mb-2">Utilisateurs</h3><p class="text-sm text-gray-600 mb-4">Liste complète des utilisateurs avec leurs informations</p><div class="flex gap-2"><button class="flex-1 bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition-colors text-sm font-medium flex items-center justify-center"><span class="material-symbols-outlined mr-1 text-sm">table_view</span>Excel</button><button class="flex-1 bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700 transition-colors text-sm font-medium flex items-center justify-center"><span class="material-symbols-outlined mr-1 text-sm">picture_as_pdf</span>PDF</button></div></div>

<div class="bg-white rounded-lg shadow-sm border border-gray-100 p-6 hover:shadow-md transition-shadow"><div class="flex items-center justify-between mb-4"><div class="bg-purple-50 p-3 rounded-full"><span class="material-symbols-outlined text-purple-600">movie</span></div><span class="px-2.5 py-1 bg-purple-100 text-purple-800 text-xs font-medium rounded-full">Disponible</span></div><h3 class="text-lg font-bold text-gray-900 mb-2">Catalogue</h3><p class="text-sm text-gray-600 mb-4">Films et séries de la plateforme</p><div class="flex gap-2"><button class="flex-1 bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition-colors text-sm font-medium flex items-center justify-center"><span class="material-symbols-outlined mr-1 text-sm">table_view</span>Excel</button><button class="flex-1 bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700 transition-colors text-sm font-medium flex items-center justify-center"><span class="material-symbols-outlined mr-1 text-sm">picture_as_pdf</span>PDF</button></div></div>

<div class="bg-white rounded-lg shadow-sm border border-gray-100 p-6 hover:shadow-md transition-shadow"><div class="flex items-center justify-between mb-4"><div class="bg-yellow-50 p-3 rounded-full"><span class="material-symbols-outlined text-yellow-600">star</span></div><span class="px-2.5 py-1 bg-yellow-100 text-yellow-800 text-xs font-medium rounded-full">Disponible</span></div><h3 class="text-lg font-bold text-gray-900 mb-2">Avis</h3><p class="text-sm text-gray-600 mb-4">Tous les avis et notes des utilisateurs</p><div class="flex gap-2"><button class="flex-1 bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition-colors text-sm font-medium flex items-center justify-center"><span class="material-symbols-outlined mr-1 text-sm">table_view</span>Excel</button><button class="flex-1 bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700 transition-colors text-sm font-medium flex items-center justify-center"><span class="material-symbols-outlined mr-1 text-sm">picture_as_pdf</span>PDF</button></div></div>

<div class="bg-white rounded-lg shadow-sm border border-gray-100 p-6 hover:shadow-md transition-shadow"><div class="flex items-center justify-between mb-4"><div class="bg-green-50 p-3 rounded-full"><span class="material-symbols-outlined text-green-600">payments</span></div><span class="px-2.5 py-1 bg-green-100 text-green-800 text-xs font-medium rounded-full">Disponible</span></div><h3 class="text-lg font-bold text-gray-900 mb-2">Transactions</h3><p class="text-sm text-gray-600 mb-4">Historique complet des paiements</p><div class="flex gap-2"><button class="flex-1 bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition-colors text-sm font-medium flex items-center justify-center"><span class="material-symbols-outlined mr-1 text-sm">table_view</span>Excel</button><button class="flex-1 bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700 transition-colors text-sm font-medium flex items-center justify-center"><span class="material-symbols-outlined mr-1 text-sm">picture_as_pdf</span>PDF</button></div></div>

<div class="bg-white rounded-lg shadow-sm border border-gray-100 p-6 hover:shadow-md transition-shadow"><div class="flex items-center justify-between mb-4"><div class="bg-pink-50 p-3 rounded-full"><span class="material-symbols-outlined text-pink-600">confirmation_number</span></div><span class="px-2.5 py-1 bg-pink-100 text-pink-800 text-xs font-medium rounded-full">Disponible</span></div><h3 class="text-lg font-bold text-gray-900 mb-2">Billets</h3><p class="text-sm text-gray-600 mb-4">Réservations et achats de billets</p><div class="flex gap-2"><button class="flex-1 bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition-colors text-sm font-medium flex items-center justify-center"><span class="material-symbols-outlined mr-1 text-sm">table_view</span>Excel</button><button class="flex-1 bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700 transition-colors text-sm font-medium flex items-center justify-center"><span class="material-symbols-outlined mr-1 text-sm">picture_as_pdf</span>PDF</button></div></div>

<div class="bg-white rounded-lg shadow-sm border border-gray-100 p-6 hover:shadow-md transition-shadow"><div class="flex items-center justify-between mb-4"><div class="bg-red-50 p-3 rounded-full"><span class="material-symbols-outlined text-red-600">analytics</span></div><span class="px-2.5 py-1 bg-red-100 text-red-800 text-xs font-medium rounded-full">Disponible</span></div><h3 class="text-lg font-bold text-gray-900 mb-2">Rapport complet</h3><p class="text-sm text-gray-600 mb-4">Rapport global de la plateforme</p><div class="flex gap-2"><button class="flex-1 bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition-colors text-sm font-medium flex items-center justify-center"><span class="material-symbols-outlined mr-1 text-sm">table_view</span>Excel</button><button class="flex-1 bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700 transition-colors text-sm font-medium flex items-center justify-center"><span class="material-symbols-outlined mr-1 text-sm">picture_as_pdf</span>PDF</button></div></div>
</div>

<div class="mt-6 bg-blue-50 border border-blue-200 rounded-lg p-4"><div class="flex items-start"><span class="material-symbols-outlined text-blue-600 mr-2 mt-0.5">info</span><div><h3 class="font-semibold text-blue-900 mb-1">Information</h3><p class="text-blue-800 text-sm">Les exports sont générés en temps réel. Les fichiers volumineux peuvent prendre quelques secondes.</p></div></div></div>
@endsection
