@extends('layouts.app')
@section('title', 'Créer talent - BlackCine Admin')
@section('content')
<div class="mb-6 flex justify-between items-center"><div><h1 class="text-3xl font-bold text-gray-800">Créer un talent</h1><p class="text-gray-600 mt-2">Ajoutez un nouveau talent à la plateforme</p></div><a href="{{ route('admin.community.talents.index') }}" class="text-gray-600 hover:text-gray-900 flex items-center px-3 py-2 rounded-lg hover:bg-gray-100 transition-colors"><span class="material-symbols-outlined mr-1">arrow_back</span>Retour</a></div>

<form action="{{ route('admin.community.talents.store') }}" method="POST" enctype="multipart/form-data">@csrf
<div class="grid grid-cols-1 lg:grid-cols-3 gap-8"><div class="lg:col-span-2 space-y-6">
<div class="bg-white rounded-xl shadow-sm border border-gray-100 p-6"><h3 class="text-lg font-semibold text-gray-800 mb-4 border-b pb-2">Informations personnelles</h3><div class="space-y-6"><div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium text-gray-700 mb-1">Prénom <span class="text-red-500">*</span></label><input type="text" name="first_name" value="{{ old('first_name') }}" required class="w-full rounded-lg border-gray-300 focus:border-red-500 focus:ring focus:ring-red-200 focus:ring-opacity-50 transition-colors shadow-sm"></div><div><label class="block text-sm font-medium text-gray-700 mb-1">Nom <span class="text-red-500">*</span></label><input type="text" name="last_name" value="{{ old('last_name') }}" required class="w-full rounded-lg border-gray-300 focus:border-red-500 focus:ring focus:ring-red-200 focus:ring-opacity-50 transition-colors shadow-sm"></div></div><div><label class="block text-sm font-medium text-gray-700 mb-1">Email <span class="text-red-500">*</span></label><input type="email" name="email" value="{{ old('email') }}" required class="w-full rounded-lg border-gray-300 focus:border-red-500 focus:ring focus:ring-red-200 focus:ring-opacity-50 transition-colors shadow-sm"></div><div><label class="block text-sm font-medium text-gray-700 mb-1">Téléphone</label><input type="tel" name="phone" value="{{ old('phone') }}" class="w-full rounded-lg border-gray-300 focus:border-red-500 focus:ring focus:ring-red-200 focus:ring-opacity-50 transition-colors shadow-sm"></div><div><label class="block text-sm font-medium text-gray-700 mb-1">Biographie</label><textarea name="bio" rows="4" class="w-full rounded-lg border-gray-300 focus:border-red-500 focus:ring focus:ring-red-200 focus:ring-opacity-50 transition-colors shadow-sm">{{ old('bio') }}</textarea></div><div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium text-gray-700 mb-1">Ville</label><input type="text" name="city" value="{{ old('city') }}" class="w-full rounded-lg border-gray-300 focus:border-red-500 focus:ring focus:ring-red-200 focus:ring-opacity-50 transition-colors shadow-sm"></div><div><label class="block text-sm font-medium text-gray-700 mb-1">Pays</label><input type="text" name="country" value="{{ old('country') }}" class="w-full rounded-lg border-gray-300 focus:border-red-500 focus:ring focus:ring-red-200 focus:ring-opacity-50 transition-colors shadow-sm"></div></div></div></div>

<div class="bg-white rounded-xl shadow-sm border border-gray-100 p-6"><h3 class="text-lg font-semibold text-gray-800 mb-4 border-b pb-2">Compétences</h3><div class="space-y-4"><div><label class="block text-sm font-medium text-gray-700 mb-1">Profession principale</label><select name="profession" class="w-full rounded-lg border-gray-300 focus:border-red-500 focus:ring focus:ring-red-200 focus:ring-opacity-50 transition-colors shadow-sm"><option value="">Sélectionner</option><option value="actor">Acteur/Actrice</option><option value="director">Réalisateur/Réalisatrice</option><option value="screenwriter">Scénariste</option><option value="producer">Producteur/Productrice</option><option value="cinematographer">Directeur/Directrice photo</option><option value="editor">Monteur/Monteuse</option><option value="composer">Compositeur/Compositrice</option><option value="other">Autre</option></select></div><div><label class="block text-sm font-medium text-gray-700 mb-1">Compétences (séparées par des virgules)</label><input type="text" name="skills" value="{{ old('skills') }}" placeholder="Ex: Comédie, Action, Improvisation" class="w-full rounded-lg border-gray-300 focus:border-red-500 focus:ring focus:ring-red-200 focus:ring-opacity-50 transition-colors shadow-sm"></div></div></div>

<div class="bg-white rounded-xl shadow-sm border border-gray-100 p-6"><h3 class="text-lg font-semibold text-gray-800 mb-4 border-b pb-2">Réseaux sociaux</h3><div class="space-y-3"><div><label class="block text-sm font-medium text-gray-700 mb-1">Site web</label><input type="url" name="website" value="{{ old('website') }}" placeholder="https://" class="w-full rounded-lg border-gray-300 focus:border-red-500 focus:ring focus:ring-red-200 focus:ring-opacity-50 transition-colors shadow-sm"></div><div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium text-gray-700 mb-1">Instagram</label><input type="text" name="instagram" value="{{ old('instagram') }}" placeholder="@username" class="w-full rounded-lg border-gray-300 focus:border-red-500 focus:ring focus:ring-red-200 focus:ring-opacity-50 transition-colors shadow-sm"></div><div><label class="block text-sm font-medium text-gray-700 mb-1">Twitter</label><input type="text" name="twitter" value="{{ old('twitter') }}" placeholder="@username" class="w-full rounded-lg border-gray-300 focus:border-red-500 focus:ring focus:ring-red-200 focus:ring-opacity-50 transition-colors shadow-sm"></div></div></div></div>
</div>

<div class="lg:col-span-1 space-y-6">
<div class="bg-white rounded-xl shadow-sm border border-gray-100 p-6"><h3 class="text-lg font-semibold text-gray-800 mb-4 border-b pb-2">Photo de profil</h3><input type="file" name="profile_photo" id="profilePhoto" accept="image/*" class="hidden"><label for="profilePhoto" class="cursor-pointer block"><div class="border-2 border-dashed border-gray-300 rounded-lg p-6 text-center hover:border-red-400 transition-colors"><span class="material-symbols-outlined text-4xl text-gray-300 mb-2 block">person</span><p class="text-sm text-gray-600">Cliquez pour uploader</p><p class="text-xs text-gray-400 mt-1">PNG, JPG (max 2MB)</p></div></label></div>

<div class="bg-white rounded-xl shadow-sm border border-gray-100 p-6"><h3 class="text-lg font-semibold text-gray-800 mb-4 border-b pb-2">Expérience</h3><div><label class="block text-sm font-medium text-gray-700 mb-1">Années d'expérience</label><input type="number" name="years_experience" value="{{ old('years_experience', 0) }}" min="0" class="w-full rounded-lg border-gray-300 focus:border-red-500 focus:ring focus:ring-red-200 focus:ring-opacity-50 transition-colors shadow-sm"></div></div>

<div class="bg-white rounded-xl shadow-sm border border-gray-100 p-6"><h3 class="text-lg font-semibold text-gray-800 mb-4 border-b pb-2">Visibilité</h3><label class="flex items-center p-3 bg-gray-50 rounded-lg"><input type="checkbox" name="is_verified" value="1" {{ old('is_verified') ? 'checked' : '' }} class="h-4 w-4 text-red-600 rounded"><span class="ml-2 text-sm font-medium flex items-center"><span class="material-symbols-outlined text-blue-600 mr-1 text-sm">verified</span>Talent vérifié</span></label></div>

<div class="bg-white rounded-xl shadow-sm border border-gray-100 p-6"><div class="space-y-3"><button type="submit" class="w-full bg-red-600 text-white py-2.5 px-4 rounded-lg hover:bg-red-700 transition-all shadow-md font-medium flex justify-center items-center"><span class="material-symbols-outlined mr-2 text-sm">save</span>Créer</button><a href="{{ route('admin.community.talents.index') }}" class="block w-full bg-gray-100 text-gray-700 py-2.5 px-4 rounded-lg hover:bg-gray-200 transition-all font-medium text-center">Annuler</a></div></div>
</div></div>
</form>
@endsection
